package database;
// Generated May 28, 2018 1:27:31 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * DonatorskiUgovor generated by hbm2java
 */
public class DonatorskiUgovor  implements java.io.Serializable {


     private Integer idDUgov;
     private int idKomp;
     private int idPaket;
     private int procVrednost;
     private String opis;
     private int kolicina;
     private Date datumUgovora;
     private String status;
     private Date datumIsporuke;
     private Date datumIsticanja;

    public DonatorskiUgovor() {
    }

    public DonatorskiUgovor(int idKomp, int idPaket, int procVrednost, String opis, int kolicina, Date datumUgovora, String status, Date datumIsporuke, Date datumIsticanja) {
       this.idKomp = idKomp;
       this.idPaket = idPaket;
       this.procVrednost = procVrednost;
       this.opis = opis;
       this.kolicina = kolicina;
       this.datumUgovora = datumUgovora;
       this.status = status;
       this.datumIsporuke = datumIsporuke;
       this.datumIsticanja = datumIsticanja;
    }
   
    public Integer getIdDUgov() {
        return this.idDUgov;
    }
    
    public void setIdDUgov(Integer idDUgov) {
        this.idDUgov = idDUgov;
    }
    public int getIdKomp() {
        return this.idKomp;
    }
    
    public void setIdKomp(int idKomp) {
        this.idKomp = idKomp;
    }
    public int getIdPaket() {
        return this.idPaket;
    }
    
    public void setIdPaket(int idPaket) {
        this.idPaket = idPaket;
    }
    public int getProcVrednost() {
        return this.procVrednost;
    }
    
    public void setProcVrednost(int procVrednost) {
        this.procVrednost = procVrednost;
    }
    public String getOpis() {
        return this.opis;
    }
    
    public void setOpis(String opis) {
        this.opis = opis;
    }
    public int getKolicina() {
        return this.kolicina;
    }
    
    public void setKolicina(int kolicina) {
        this.kolicina = kolicina;
    }
    public Date getDatumUgovora() {
        return this.datumUgovora;
    }
    
    public void setDatumUgovora(Date datumUgovora) {
        this.datumUgovora = datumUgovora;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Date getDatumIsporuke() {
        return this.datumIsporuke;
    }
    
    public void setDatumIsporuke(Date datumIsporuke) {
        this.datumIsporuke = datumIsporuke;
    }
    public Date getDatumIsticanja() {
        return this.datumIsticanja;
    }
    
    public void setDatumIsticanja(Date datumIsticanja) {
        this.datumIsticanja = datumIsticanja;
    }




}


