package database;
// Generated May 28, 2018 1:27:31 PM by Hibernate Tools 4.3.1



/**
 * Kompanija generated by hbm2java
 */
public class Kompanija  implements java.io.Serializable {


     private Integer idKomp;
     private String naziv;
     private String adresa;
     private String grad;
     private String postanskiBroj;
     private String drzava;
     private String racun;
     private String valuta;
     private String pib;
     private String kontakt1;
     private String kontakt2;
     private String kontakt3;
     private String kontakt4;
     private String kontakt5;
     private String kontOsoba;
     private String kontTelef;
     private String kontEmail;
     private String logoLink;
     private String webLink;
     private String opis;

    public Kompanija() {
    }

    public Kompanija(String naziv, String adresa, String grad, String postanskiBroj, String drzava, String racun, String valuta, String pib, String kontakt1, String kontakt2, String kontakt3, String kontakt4, String kontakt5, String kontOsoba, String kontTelef, String kontEmail, String logoLink, String webLink, String opis) {
       this.naziv = naziv;
       this.adresa = adresa;
       this.grad = grad;
       this.postanskiBroj = postanskiBroj;
       this.drzava = drzava;
       this.racun = racun;
       this.valuta = valuta;
       this.pib = pib;
       this.kontakt1 = kontakt1;
       this.kontakt2 = kontakt2;
       this.kontakt3 = kontakt3;
       this.kontakt4 = kontakt4;
       this.kontakt5 = kontakt5;
       this.kontOsoba = kontOsoba;
       this.kontTelef = kontTelef;
       this.kontEmail = kontEmail;
       this.logoLink = logoLink;
       this.webLink = webLink;
       this.opis = opis;
    }
   
    public Integer getIdKomp() {
        return this.idKomp;
    }
    
    public void setIdKomp(Integer idKomp) {
        this.idKomp = idKomp;
    }
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }
    public String getAdresa() {
        return this.adresa;
    }
    
    public void setAdresa(String adresa) {
        this.adresa = adresa;
    }
    public String getGrad() {
        return this.grad;
    }
    
    public void setGrad(String grad) {
        this.grad = grad;
    }
    public String getPostanskiBroj() {
        return this.postanskiBroj;
    }
    
    public void setPostanskiBroj(String postanskiBroj) {
        this.postanskiBroj = postanskiBroj;
    }
    public String getDrzava() {
        return this.drzava;
    }
    
    public void setDrzava(String drzava) {
        this.drzava = drzava;
    }
    public String getRacun() {
        return this.racun;
    }
    
    public void setRacun(String racun) {
        this.racun = racun;
    }
    public String getValuta() {
        return this.valuta;
    }
    
    public void setValuta(String valuta) {
        this.valuta = valuta;
    }
    public String getPib() {
        return this.pib;
    }
    
    public void setPib(String pib) {
        this.pib = pib;
    }
    public String getKontakt1() {
        return this.kontakt1;
    }
    
    public void setKontakt1(String kontakt1) {
        this.kontakt1 = kontakt1;
    }
    public String getKontakt2() {
        return this.kontakt2;
    }
    
    public void setKontakt2(String kontakt2) {
        this.kontakt2 = kontakt2;
    }
    public String getKontakt3() {
        return this.kontakt3;
    }
    
    public void setKontakt3(String kontakt3) {
        this.kontakt3 = kontakt3;
    }
    public String getKontakt4() {
        return this.kontakt4;
    }
    
    public void setKontakt4(String kontakt4) {
        this.kontakt4 = kontakt4;
    }
    public String getKontakt5() {
        return this.kontakt5;
    }
    
    public void setKontakt5(String kontakt5) {
        this.kontakt5 = kontakt5;
    }
    public String getKontOsoba() {
        return this.kontOsoba;
    }
    
    public void setKontOsoba(String kontOsoba) {
        this.kontOsoba = kontOsoba;
    }
    public String getKontTelef() {
        return this.kontTelef;
    }
    
    public void setKontTelef(String kontTelef) {
        this.kontTelef = kontTelef;
    }
    public String getKontEmail() {
        return this.kontEmail;
    }
    
    public void setKontEmail(String kontEmail) {
        this.kontEmail = kontEmail;
    }
    public String getLogoLink() {
        return this.logoLink;
    }
    
    public void setLogoLink(String logoLink) {
        this.logoLink = logoLink;
    }
    public String getWebLink() {
        return this.webLink;
    }
    
    public void setWebLink(String webLink) {
        this.webLink = webLink;
    }
    public String getOpis() {
        return this.opis;
    }
    
    public void setOpis(String opis) {
        this.opis = opis;
    }




}


