package database;
// Generated May 28, 2018 1:27:31 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Korisnik generated by hbm2java
 */
public class Korisnik  implements java.io.Serializable {


     private String username;
     private String password;
     private String ime;
     private String prezime;
     private String email;
     private String institucija;
     private String pol;
     private Date datumRodjenja;
     private int tip;
     private int zahtev;

    public Korisnik() {
    }

    public Korisnik(String username, String password, String ime, String prezime, String email, String institucija, String pol, Date datumRodjenja, int tip, int zahtev) {
       this.username = username;
       this.password = password;
       this.ime = ime;
       this.prezime = prezime;
       this.email = email;
       this.institucija = institucija;
       this.pol = pol;
       this.datumRodjenja = datumRodjenja;
       this.tip = tip;
       this.zahtev = zahtev;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getIme() {
        return this.ime;
    }
    
    public void setIme(String ime) {
        this.ime = ime;
    }
    public String getPrezime() {
        return this.prezime;
    }
    
    public void setPrezime(String prezime) {
        this.prezime = prezime;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getInstitucija() {
        return this.institucija;
    }
    
    public void setInstitucija(String institucija) {
        this.institucija = institucija;
    }
    public String getPol() {
        return this.pol;
    }
    
    public void setPol(String pol) {
        this.pol = pol;
    }
    public Date getDatumRodjenja() {
        return this.datumRodjenja;
    }
    
    public void setDatumRodjenja(Date datumRodjenja) {
        this.datumRodjenja = datumRodjenja;
    }
    public int getTip() {
        return this.tip;
    }
    
    public void setTip(int tip) {
        this.tip = tip;
    }
    public int getZahtev() {
        return this.zahtev;
    }
    
    public void setZahtev(int zahtev) {
        this.zahtev = zahtev;
    }




}


