package database;
// Generated May 28, 2018 1:27:31 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * NovcaniUgovor generated by hbm2java
 */
public class NovcaniUgovor  implements java.io.Serializable {


     private Integer idNUgov;
     private int idKomp;
     private int idPaket;
     private int vrednost;
     private Date datumUgovora;
     private String status;
     private int poslataFaktura;
     private int izvrsenaUplata;
     private Date datumUplate;
     private Date datumIsticanja;

    public NovcaniUgovor() {
    }

    public NovcaniUgovor(int idKomp, int idPaket, int vrednost, Date datumUgovora, String status, int poslataFaktura, int izvrsenaUplata, Date datumUplate, Date datumIsticanja) {
       this.idKomp = idKomp;
       this.idPaket = idPaket;
       this.vrednost = vrednost;
       this.datumUgovora = datumUgovora;
       this.status = status;
       this.poslataFaktura = poslataFaktura;
       this.izvrsenaUplata = izvrsenaUplata;
       this.datumUplate = datumUplate;
       this.datumIsticanja = datumIsticanja;
    }
   
    public Integer getIdNUgov() {
        return this.idNUgov;
    }
    
    public void setIdNUgov(Integer idNUgov) {
        this.idNUgov = idNUgov;
    }
    public int getIdKomp() {
        return this.idKomp;
    }
    
    public void setIdKomp(int idKomp) {
        this.idKomp = idKomp;
    }
    public int getIdPaket() {
        return this.idPaket;
    }
    
    public void setIdPaket(int idPaket) {
        this.idPaket = idPaket;
    }
    public int getVrednost() {
        return this.vrednost;
    }
    
    public void setVrednost(int vrednost) {
        this.vrednost = vrednost;
    }
    public Date getDatumUgovora() {
        return this.datumUgovora;
    }
    
    public void setDatumUgovora(Date datumUgovora) {
        this.datumUgovora = datumUgovora;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public int getPoslataFaktura() {
        return this.poslataFaktura;
    }
    
    public void setPoslataFaktura(int poslataFaktura) {
        this.poslataFaktura = poslataFaktura;
    }
    public int getIzvrsenaUplata() {
        return this.izvrsenaUplata;
    }
    
    public void setIzvrsenaUplata(int izvrsenaUplata) {
        this.izvrsenaUplata = izvrsenaUplata;
    }
    public Date getDatumUplate() {
        return this.datumUplate;
    }
    
    public void setDatumUplate(Date datumUplate) {
        this.datumUplate = datumUplate;
    }
    public Date getDatumIsticanja() {
        return this.datumIsticanja;
    }
    
    public void setDatumIsticanja(Date datumIsticanja) {
        this.datumIsticanja = datumIsticanja;
    }




}


