package database;
// Generated May 28, 2018 1:27:31 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Oglas generated by hbm2java
 */
public class Oglas  implements java.io.Serializable {


     private Integer idOglas;
     private String naslov;
     private String opis;
     private int strucnaPraksa;
     private int zaposlenje;
     private Date datum;
     private Date vreme;
     private int idKomp;

    public Oglas() {
    }

    public Oglas(String naslov, String opis, int strucnaPraksa, int zaposlenje, Date datum, Date vreme, int idKomp) {
       this.naslov = naslov;
       this.opis = opis;
       this.strucnaPraksa = strucnaPraksa;
       this.zaposlenje = zaposlenje;
       this.datum = datum;
       this.vreme = vreme;
       this.idKomp = idKomp;
    }
   
    public Integer getIdOglas() {
        return this.idOglas;
    }
    
    public void setIdOglas(Integer idOglas) {
        this.idOglas = idOglas;
    }
    public String getNaslov() {
        return this.naslov;
    }
    
    public void setNaslov(String naslov) {
        this.naslov = naslov;
    }
    public String getOpis() {
        return this.opis;
    }
    
    public void setOpis(String opis) {
        this.opis = opis;
    }
    public int getStrucnaPraksa() {
        return this.strucnaPraksa;
    }
    
    public void setStrucnaPraksa(int strucnaPraksa) {
        this.strucnaPraksa = strucnaPraksa;
    }
    public int getZaposlenje() {
        return this.zaposlenje;
    }
    
    public void setZaposlenje(int zaposlenje) {
        this.zaposlenje = zaposlenje;
    }
    public Date getDatum() {
        return this.datum;
    }
    
    public void setDatum(Date datum) {
        this.datum = datum;
    }
    public Date getVreme() {
        return this.vreme;
    }
    
    public void setVreme(Date vreme) {
        this.vreme = vreme;
    }
    public int getIdKomp() {
        return this.idKomp;
    }
    
    public void setIdKomp(int idKomp) {
        this.idKomp = idKomp;
    }




}


