package database;
// Generated May 28, 2018 1:27:31 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Predavanje generated by hbm2java
 */
public class Predavanje  implements java.io.Serializable {


     private Integer idPred;
     private String naslovRs;
     private String naslovEn;
     private String opisRs;
     private String opisEn;
     private Date datum;
     private Date vreme;
     private String sala;
     private String predavac;
     private String biografija;
     private int idKomp;
     private int proslo;

    public Predavanje() {
    }

    public Predavanje(String naslovRs, String naslovEn, String opisRs, String opisEn, Date datum, Date vreme, String sala, String predavac, String biografija, int idKomp, int proslo) {
       this.naslovRs = naslovRs;
       this.naslovEn = naslovEn;
       this.opisRs = opisRs;
       this.opisEn = opisEn;
       this.datum = datum;
       this.vreme = vreme;
       this.sala = sala;
       this.predavac = predavac;
       this.biografija = biografija;
       this.idKomp = idKomp;
       this.proslo = proslo;
    }
   
    public Integer getIdPred() {
        return this.idPred;
    }
    
    public void setIdPred(Integer idPred) {
        this.idPred = idPred;
    }
    public String getNaslovRs() {
        return this.naslovRs;
    }
    
    public void setNaslovRs(String naslovRs) {
        this.naslovRs = naslovRs;
    }
    public String getNaslovEn() {
        return this.naslovEn;
    }
    
    public void setNaslovEn(String naslovEn) {
        this.naslovEn = naslovEn;
    }
    public String getOpisRs() {
        return this.opisRs;
    }
    
    public void setOpisRs(String opisRs) {
        this.opisRs = opisRs;
    }
    public String getOpisEn() {
        return this.opisEn;
    }
    
    public void setOpisEn(String opisEn) {
        this.opisEn = opisEn;
    }
    public Date getDatum() {
        return this.datum;
    }
    
    public void setDatum(Date datum) {
        this.datum = datum;
    }
    public Date getVreme() {
        return this.vreme;
    }
    
    public void setVreme(Date vreme) {
        this.vreme = vreme;
    }
    public String getSala() {
        return this.sala;
    }
    
    public void setSala(String sala) {
        this.sala = sala;
    }
    public String getPredavac() {
        return this.predavac;
    }
    
    public void setPredavac(String predavac) {
        this.predavac = predavac;
    }
    public String getBiografija() {
        return this.biografija;
    }
    
    public void setBiografija(String biografija) {
        this.biografija = biografija;
    }
    public int getIdKomp() {
        return this.idKomp;
    }
    
    public void setIdKomp(int idKomp) {
        this.idKomp = idKomp;
    }
    public int getProslo() {
        return this.proslo;
    }
    
    public void setProslo(int proslo) {
        this.proslo = proslo;
    }




}


