package database;
// Generated May 28, 2018 1:27:31 PM by Hibernate Tools 4.3.1



/**
 * Status generated by hbm2java
 */
public class Status  implements java.io.Serializable {


     private Integer idStatus;
     private String naziv;

    public Status() {
    }

    public Status(String naziv) {
       this.naziv = naziv;
    }
   
    public Integer getIdStatus() {
        return this.idStatus;
    }
    
    public void setIdStatus(Integer idStatus) {
        this.idStatus = idStatus;
    }
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }




}


